CREATE DATABASE swiftonsnap;
CREATE TABLE users(id SERIAL, device_token VARCHAR(255) UNIQUE);
CREATE TABLE events(id SERIAL, ended_at TIMESTAMP WITHOUT TIME ZONE, name TEXT, started_at TIMESTAMP WITHOUT TIME ZONE, user_id INTEGER, address TEXT, lat DOUBLE PRECISION, lon DOUBLE PRECISION);
